apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
spec:
  ports:
  - name: http
    port: 6333
    protocol: TCP
    targetPort: 6333
  sessionAffinity: ClientIP
  type: ClusterIP
  selector:
    app: qdrant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  labels:
    app: qdrant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:v1.15
          ports:
            - containerPort: 6333
          volumeMounts:
            - name: qdrant-pvc
              mountPath: /qdrant/storage
      volumes:
        - name: qdrant-pvc
          persistentVolumeClaim:
            claimName: qdrant-pvc
